project:
  type: website
  output-dir: docs
website:
  title: "Daniel Gavidia"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Sobre mí
      - href: research.qmd
        text: Investigaciones
      - href: teaching.qmd
        text: Docencia
      - section: Resources
        contents:
          - href: code.qmd
            text: Códigos
          - href: contact.qmd
            text: Contáctame
format:
  html:
    theme: darkly
    toc: true
    css: styles.css
